services:
  backend:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DB_HOST=db
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"                          # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql           # Persist data
volumes:
  static_volume:
  media_volume:
  mysql_data: